version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 5
      
  
  testa:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hello"
      - run: sleep 5
  testb:
    docker: 
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "a localized salut"
      - run: sleep 5
     
     
    deploy:
      docker:
        -image: circleci/ruby:2.4.1
      steps:
        - checkout
        - run: echo "a final goodbye"
        - run: sleep 5
        
        
workflows: 
  version: 2
  build_and_test:
    jobs:
     - build
     - testa:
        requires:
          - build 
     - testb: 
        requires:
          - build
     - deploy: 
        requires:
          - testa
          - testb
