version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: mkdir -p my_workspace
        # making folder called my_workspace
      - run: echo "hello world" > my_workspace/echo-output
      - persist_to_workspace:
          # must be absolute path or relative pat from working_directory
          root: my_workspace
          # must be relative path from root
          paths:
            - echo-output
  testa:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
          # must be absolute path or relative path from working_directory
          at: my_workspace
          
      - run: cat my_workspace/echo-output
          # show me content of the file
      
  testb:
    docker: 
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
          # must be absolute path or relative path from working_directory
          - at: my_workspace
      
      - run: |
          if [[ $(cat my_workspace/echo-output) == "trying out workspaces" ]]; then
            echo "it worked"
          esle
            echo "nope!"; exit 1
          fi
     
  deploy:
    docker:
      -image: circleci/ruby:2.4.1
    steps:
        - attach_workspace:
            #must be absolute path or relative path from working_directory
            at: my_workspace
        -run: |
            echo "deploy message!"
            cat my_workspace/echo-output
        
workflows: 
  version: 2
  build_and_test:
    jobs:
      - build
      - testa:
          requires:
            - build 
      - testb: 
          requires:
            - build
      - deploy: 
          requires:
            - testa
            - testb
